import { CommentType, UserType } from "@/types/common/userType";
import { PlayerListItem, PlaylistType } from "@/types/common/Song&PlaylistType";

export const sampleUser: UserType = {
  id: "admin",
  email: "lee@gmail.com",
  nickname: "Lee",
  password: "1234",
  createdAt: "2021-08-01T00:00:00.000Z",
  updatedAt: "2021-08-01T00:00:00.000Z",
  isBlocked: false,
  bio: "This is the test bio admin 1",
  profilePic:
    "https://res.cloudinary.com/dolziw8fv/image/upload/v1674146352/htdvtatpybxqeoybiqbl.png",
  followers: [],
  following: [],
  playlists: [
    {
      id: "second_list",
      title: "Second Test",
      description: "This is the second list local test data",
      coverImage:
        "https://res.cloudinary.com/dolziw8fv/image/upload/v1680175878/e9u4xoelipawp2wbxpyd.jpg",
      songs: [
        {
          id: "first_list_1",
          artist: "Sade",
          title: "Smooth Operator",
          url: "https://www.youtube.com/watch?v=4TYv2PhG89A",
          playedCount: 10,
          likedCount: 20,
        },
        {
          id: "first_list_2",
          artist: "Utata Hikaru",
          title: "In My Room",
          url: "https://soundcloud.com/gum_mp3/in-my-room-utada-hikaru-db-garage-mix?si=7329048ff1f8437cb3f775d34b745e38&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
          playedCount: 10,
          likedCount: 2,
        },
      ],
      authorId: "1",
      author: {
        id: "admin",
        email: "",
        playlists: [],
        followers: [],
        following: [],
        createdAt: "",
        updatedAt: "",
        isBlocked: false,
        bio: "",
        profilePic: "",
        nickname: "",
        password: "",
        playedCount: 0,
        likedSongs: [],
        likedPlaylists: [],
        myComments: [],
        profileComments: [],
      },
      createdAt: "2021-08-01T00:00:00.000Z",
      updatedAt: "2021-08-01T00:00:00.000Z",
      playCount: 10,
      likedBy: [],
      comments: [],
    },
    {
      id: "second_list",
      title: "Second Test",
      description: "This is the second list local test data",
      coverImage:
        "https://res.cloudinary.com/dolziw8fv/image/upload/v1680175878/e9u4xoelipawp2wbxpyd.jpg",
      songs: [
        {
          id: "first_list_1",
          artist: "Sade",
          title: "Smooth Operator",
          url: "https://www.youtube.com/watch?v=4TYv2PhG89A",
          playedCount: 10,
          likedCount: 20,
        },
        {
          id: "first_list_2",
          artist: "Utata Hikaru",
          title: "In My Room",
          url: "https://soundcloud.com/gum_mp3/in-my-room-utada-hikaru-db-garage-mix?si=7329048ff1f8437cb3f775d34b745e38&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
          playedCount: 10,
          likedCount: 2,
        },
      ],
      authorId: "1",
      author: {
        id: "admin",
        email: "",
        playlists: [],
        followers: [],
        following: [],
        createdAt: "",
        updatedAt: "",
        isBlocked: false,
        bio: "",
        profilePic: "",
        nickname: "",
        password: "",
        playedCount: 0,
        likedSongs: [],
        likedPlaylists: [],
        myComments: [],
        profileComments: [],
      },
      createdAt: "2021-08-01T00:00:00.000Z",
      updatedAt: "2021-08-01T00:00:00.000Z",
      playCount: 10,
      likedBy: [],
      comments: [],
    },
  ],
  likedSongs: [],
  likedPlaylists: [],
  myComments: [
    {
      id: "1",
      comment: "댓글1 tester tester tester",
      isPrivate: false,
      type: "playlist",
      author: {} as UserType,
      authorId: "1",
      playlistId: "1",
      createdAt: "2021-08-01T00:00:00.000Z",
      updatedAt: "2021-08-01T00:00:00.000Z",
    },
    {
      id: "2",
      comment: "MEOWOWOEOWOEOWOEOW",
      isPrivate: false,
      type: "playlist",
      author: {} as UserType,
      authorId: "1",
      playlistId: "1",
      createdAt: "2021-08-01T00:00:00.000Z",
      updatedAt: "2021-08-01T00:00:00.000Z",
    },
    {
      id: "3",
      comment: "댓글3 tester tester tester",
      isPrivate: false,
      type: "playlist",
      author: {} as UserType,
      authorId: "1",
      playlistId: "1",
      createdAt: "2021-08-01T00:00:00.000Z",
      updatedAt: "2021-08-01T00:00:00.000Z",
    },
  ],
  profileComments: [],
  playedCount: 3220,
};

export const sampleUser2: UserType = {
  id: "admin",
  email: "lee@gmail.com",
  nickname: "Lee2",
  password: "1234",
  createdAt: "2021-08-01T00:00:00.000Z",
  updatedAt: "2021-08-01T00:00:00.000Z",
  isBlocked: false,
  bio: "This is the test bio admin 1",
  profilePic:
    "https://res.cloudinary.com/dolziw8fv/image/upload/v1689606920/616Xg2p9O2L._AC_UF1000_1000_QL80__qjrked.jpg",
  followers: [],
  following: [],
  playlists: [],
  likedSongs: [],
  likedPlaylists: [],
  myComments: [],
  profileComments: [],
  playedCount: 1000,
};

export const sampleComments1: CommentType[] = [
  {
    id: "1",
    comment: "댓글1 tester tester tester",
    isPrivate: false,
    type: "playlist",
    author: sampleUser,
    authorId: "1",
    playlistId: "1",
    createdAt: "2021-08-01T00:00:00.000Z",
    updatedAt: "2021-08-01T00:00:00.000Z",
  },
  {
    id: "2",
    comment: "MEOWOWOEOWOEOWOEOW",
    isPrivate: false,
    type: "playlist",
    author: sampleUser,
    authorId: "1",
    playlistId: "1",
    createdAt: "2021-08-01T00:00:00.000Z",
    updatedAt: "2021-08-01T00:00:00.000Z",
  },
  {
    id: "3",
    comment: "댓글3 tester tester tester",
    isPrivate: false,
    type: "playlist",
    author: sampleUser,
    authorId: "1",
    playlistId: "1",
    createdAt: "2021-08-01T00:00:00.000Z",
    updatedAt: "2021-08-01T00:00:00.000Z",
  },
  {
    id: "4",
    comment: "ㅋㅋㅋㅋㅋㅋㅋ",
    isPrivate: false,
    type: "playlist",
    author: sampleUser,
    authorId: "1",
    playlistId: "1",
    createdAt: "2021-08-01T00:00:00.000Z",
    updatedAt: "2021-08-01T00:00:00.000Z",
  },
  {
    id: "5",
    comment: "댓글1 tester tester tester",
    isPrivate: false,
    type: "playlist",
    author: sampleUser,
    authorId: "1",
    playlistId: "1",
    createdAt: "2021-08-01T00:00:00.000Z",
    updatedAt: "2021-08-01T00:00:00.000Z",
  },
];
export const sampleComments2: CommentType[] = sampleComments1.map((x) => ({
  ...x,
  id: String(Number(x.id) + 5),
  comment: "댓글2 " + x.comment,
}));
export const fakePlaylistSongsData: PlayerListItem[] = [
  {
    id: "first_list_1",
    artist: "Sade",
    title: "Smooth Operator",
    url: "https://www.youtube.com/watch?v=4TYv2PhG89A",
    playedCount: 10,
    likedCount: 20,
  },
  {
    id: "first_list_2",
    artist: "Utata Hikaru",
    title: "In My Room",
    url: "https://soundcloud.com/gum_mp3/in-my-room-utada-hikaru-db-garage-mix?si=7329048ff1f8437cb3f775d34b745e38&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
    playedCount: 10,
    likedCount: 2,
  },
  {
    id: "first_list_2",
    artist: "Delano Smith (Bandcamp test)",
    title: "Midnight Hours (Reconstructed by Carl Craig)\n",
    url: "https://delanosmithdetroit.bandcamp.com/track/midnight-hours-reconstructed-by-carl-craig",
    playedCount: 10,
    likedCount: 2,
  },
];

export const fakeFirstPlaylistData: PlaylistType = {
  id: "first_list",
  title: "First List",
  description: "This is the first list local test data",
  coverImage:
    "https://res.cloudinary.com/dolziw8fv/image/upload/v1689606968/a1346689507_65_tbj0bd.jpg",
  songs: fakePlaylistSongsData,
  authorId: sampleUser.id,
  author: sampleUser,
  createdAt: "2021-08-01T00:00:00.000Z",
  updatedAt: "2021-08-01T00:00:00.000Z",
  playCount: 10,
  likedBy: [],
  comments: sampleComments1,
};

export const fakeSecondPlaylistData: PlaylistType = {
  id: "second_list",
  title: "Second Test",
  description: "This is the second list local test data",
  coverImage:
    "https://res.cloudinary.com/dolziw8fv/image/upload/v1680175878/e9u4xoelipawp2wbxpyd.jpg",
  songs: fakePlaylistSongsData,
  authorId: sampleUser.id,
  author: sampleUser,
  createdAt: "2021-08-01T00:00:00.000Z",
  updatedAt: "2021-08-01T00:00:00.000Z",
  playCount: 10,
  likedBy: [],
  comments: sampleComments2,
};

export const fakePlayLists: PlaylistType[] = [
  fakeFirstPlaylistData,
  fakeSecondPlaylistData,
];
